from setuptools import setup, find_packages
    
setup(
    name='gpi',
    version='1.0.0',
    packages=find_packages(),
    description='Uma biblioteca qualquer para o Grupo de planejamento de intervenção',
    author='Mateus Cavalheiro Siqueira',
    author_email='wateuz@hotmail.com',
    url='',
    install_requires=[
'backports.tarfile==1.2.0',
'certifi==2025.1.31',
'charset-normalizer==3.4.1',
'docutils==0.21.2',
'id==1.5.0',
'idna==3.10',
'importlib_metadata==8.6.1',
'jaraco.classes==3.4.0',
'jaraco.context==6.0.1',
'jaraco.functools==4.1.0',
'keyring==25.6.0',
'markdown-it-py==3.0.0',
'mdurl==0.1.2',
'more-itertools==10.6.0',
'nh3==0.2.21',
'packaging==24.2',
'Pygments==2.19.1',
'pywin32-ctypes==0.2.3',
'readme_renderer==44.0',
'requests==2.32.3',
'requests-toolbelt==1.0.0',
'rfc3986==2.0.0',
'rich==13.9.4',
'twine==6.1.0',
'urllib3==2.3.0',
'zipp==3.21.0'
],
    license='MIT',
    classifiers=[
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    ],# Lista de dependências, se houver
)